[package]
name = "nft-loans-export"
version = "0.1.0"
authors = ["Nicolas KOWALSKI <kowalski.kowalskin@gmail.com>"]
edition = "2018"
description = "Messages for the p2p trading contract"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/cw-plus"
homepage = "https://cosmwasm.com"
documentation = "https://docs.cosmwasm.com"

[lib]
bench = false

[features]
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
# CosmWasm
cw20 = "0.15.1"
cw721 = "0.15.0"
cw-storage-plus = "0.15.1"
cw20-base = { version = "0.15.1", features = ["library"] }
cosmwasm-std = { version = "1.0.0" }
cosmwasm-schema = { version = "1.0.0" }

#Other Modules
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.23" }
strum = "0.25"
strum_macros = "0.25.3"

#Local Modules
utils = { path = "../utils", version = "0.1.0" }

[dev-dependencies]

